### ISSUE TITLE
Feature request: Resource Importability for BIGIP Resources

### ISSUE THREAD

**Issue by DarthVader2409** [terraform-providers/terraform-provider-bigip#120]
I understand that terraform can import one resource at a time and each resource in terraform must implement some basic logic to become importable. Currently, I don't see a way to import BIGIP resources like a ltm monitor or node.

**Comment by dannyk81** [comment]
All resources can be imported, they all implement the import function which in most cases is a simple pass-through to the read function.

I personally used the provider to import: virtual servers, pools, pool attachments (for which I implemented the [import](https://github.com/terraform-providers/terraform-provider-bigip/pull/84)), nodes, snat pools and others.

Have you tried to import? have you encountered a specific issue?

**Comment by DarthVader2409** [comment]
Ah, I see. Thank you. I am new to terraform, I was going through the website and read that for those resources that support import, they are documented at the bottom of each resource documentation page, under the Import heading. https://www.terraform.io/docs/providers/bigip/r/bigip_ltm_pool_attachment.html
But I didn't find any information about import in there.

**Comment by dannyk81** [comment]
Docs for this provider are not in the best of shapes, but the functionality is there.

I had a PR that was merged for the pool attachment import doc https://github.com/terraform-providers/terraform-provider-bigip/pull/88, not sure why it's not there on the website :man_shrugging:

**Comment by DarthVader2409** [comment]
@dannyk81 Hi Danny! Would you be able to help me with this- https://discuss.hashicorp.com/t/help-template-tf-and-user-data-yaml-tpl-flexible-assignment-of-variable/2444
