### ISSUE TITLE
Setting for bigip_ltm_virtual_server "type required

### ISSUE THREAD

**Issue by lukibahr** [terraform-providers/terraform-provider-bigip#125]
Hey folks, 

I'm looking for the setting of the type of a virtual server

![image](https://user-images.githubusercontent.com/17235051/60510493-ce9bef80-9ccf-11e9-836f-1775c018a0ce.png)

Terraform creates a virtual server with type "Performance (Layer 4)" per default but I want to create one of type "standard". 

Am I missing the required setting or anything else? 

```yaml
resource "bigip_ltm_virtual_server" "http" {
        pool = "/${var.big_ip_partition}/${var.big_ip_pool}"
        name = "/${var.big_ip_partition}/${var.big_ip_virtual_server}"
        destination = "${var.big_ip_virtual_server_ip}"
        port = "${var.big_ip_virtual_server_port}"
        ip_protocol = "tcp"
        #server_profiles = ["/Common/tcp-lan-optimized"] 
        source_address_translation = "automap"
        depends_on = ["bigip_ltm_pool.pool"]
        vlans_enabled = "true"
        #vlans = ["LAN"]`
```

**Comment by mdditt2000** [comment]
Jira TER-20

**Comment by dhawal55** [comment]
I'm running into the exact same problem. Any update on this?

**Comment by dannyk81** [comment]
BigIP defaults to `FastL4`, in order to use a `Standard` profile ensure you have this in your Virtual Server resource definition:
```
  profiles = ["/Common/tcp"]
```

**Comment by dhawal55** [comment]
When I set `profiles`, I get the following error:
```
Configuration error: Less than the required minimum number of profiles found on /partition/server: Exactly 1 of (UDP Profile (clientside), TCP Profile (clientside), SCTP Profile (clientside))
```

**Comment by dannyk81** [comment]
@dhawal55 I have hit this too, there's an issue when switching from individually set client/server profile(s) to a common profiles attribute.

I was meaning to take a look at the root cause but don't have the time, but the provider doesn't handle that currently and throws the above error.

**Comment by soumik612** [comment]
I tried the option provided by @dannyk81 and it works for me. I am able to build standard and Performance HTTP VS by modifying "profiles" attribute:
![image](https://user-images.githubusercontent.com/35273569/64704065-f23c9c80-d4ad-11e9-98b8-b251494f79fe.png)
![image](https://user-images.githubusercontent.com/35273569/64704099-02547c00-d4ae-11e9-9e41-281df574eceb.png)

**Comment by dhawal55** [comment]
@dannyk81 Thank you for your help. I will delete and try again with common profiles attribute

**Comment by dhawal55** [comment]
@dannyk81 It worked, thanks again.

**Comment by lukibahr** [comment]
solution of @dannyk81 worked for me, too! Thank you, guys
