### ISSUE TITLE
controls for policy required or optional

### ISSUE THREAD

**Issue by jlosito** [terraform-providers/terraform-provider-bigip#132]
I'm getting an error when trying to create a bigip_ltm_policy. The error states that I'm missing a required argument, controls. But the documentation states that controls is an optional argument [here](https://www.terraform.io/docs/providers/bigip/r/bigip_ltm_policy.html#controls), and I noticed that the scheme states that it's required [here](https://github.com/terraform-providers/terraform-provider-bigip/blob/master/bigip/resource_bigip_ltm_policy.go#L42-L47).

Is the controls argument required?

**Comment by scshitole** [comment]
@jlosito can you please test after the latest commit.

**Comment by jlosito** [comment]
@scshitole looks good.
