### ISSUE TITLE
rule for policy required or optional

### ISSUE THREAD

**Issue by jlosito** [terraform-providers/terraform-provider-bigip#133]
I am getting an error when trying to create an bigip_ltm_policy that states that I have insufficient rule blocks. The documentation states that rule is an optional argument [here](https://www.terraform.io/docs/providers/bigip/r/bigip_ltm_policy.html#rule), and the schema states that it is required [here](https://github.com/terraform-providers/terraform-provider-bigip/blob/master/bigip/resource_bigip_ltm_policy.go#L63-L66).

Is the rule argument optional or required?

**Comment by papineni87** [comment]
Rule argument is optional and fixed in the schema code

**Comment by papineni87** [comment]
merged in the master branch
