### ISSUE TITLE
allow uploading policies to a specific partition

### ISSUE THREAD

**Issue by jlosito** [terraform-providers/terraform-provider-bigip#135]
Currently, the ltm_policy resource does not have the ability to upload policies to a partition which is not Common.

**Comment by dannyk81** [comment]
indeed it is a bug I mentioned several times, since the Common partition is hard coded in the code.

@scshitole

**Comment by jlosito** [comment]
We have a working change that allows for uploading to a specific partition. We are planning to submit a PR once we've tested a little more.

I think the issue is a partition name is never passed to the rest client, so the rest client assumes Common since it's the default.

**Comment by dannyk81** [comment]
the issue is in the go-bigip library, specifically here https://github.com/terraform-providers/terraform-provider-bigip/blob/e6f13aa07b8783bf38af8aa34d0a59a4bb119db3/vendor/github.com/f5devcentral/go-bigip/ltm.go#L2582

as you can see `~Common~` is always added to the policy name.

**Comment by jlosito** [comment]
@scshitole Can we reopen this since the changes were reverted?
