### ISSUE TITLE
virtual server persistence_profile attribute cannot revert back to None

### ISSUE THREAD

**Issue by jlosito** [terraform-providers/terraform-provider-bigip#142]
I have a couple of VIPs which do not need any persistence profile. I'm coming across an issue where I've set the persistence_profile attribute to something such as "/Common/cookie" but then am not able to change to "None".

Here's an example of what I'm trying to explain.

First I'm creating a VIP like the following:
```
resource "bigip_ltm_virtual_server" "virtual_server" {
  name = "my_vip.my_company.com"
  ...
  persistence_profile = ["/Common/cookie"]
}
```
Then I'm trying to change the default persistence profile for the vip from "/Common/cookie" to "None" by the following:

```
resource "bigip_ltm_virtual_server" "virtual_server" {
  name = "my_vip.my_company.com"
  ...
  persistence_profile = []
}
```
What I'm observing is the terraform plan and apply look correct, the state file is changing, the terraform apply executes without errors, but the actual infrastructure still has "/Common/cookie" as its default persistence profile.

Is there some other way to change the default persistence profile that I'm missing?

**Comment by RavinderReddyF5** [comment]
https://github.com/terraform-providers/terraform-provider-bigip/issues/169
