### ISSUE TITLE
Missing Health Monitor resources : UDP / PostgreSQL

### ISSUE THREAD

**Issue by soumik612** [terraform-providers/terraform-provider-bigip#159]
I am testing a use case where we need to build health monitors of type UDP and Postgresql.
 This is how my resource looks like,
 
![image](https://user-images.githubusercontent.com/35273569/65137888-62957180-da0a-11e9-8b17-92fd51becc6e.png)

This is the error I get when I apply the resources,
![image](https://user-images.githubusercontent.com/35273569/65137942-793bc880-da0a-11e9-8f82-fc3d5be78f0f.png)

Would be great to have this feature added in TF.
Here is an output of an API query for these monitors, if it helps
![image](https://user-images.githubusercontent.com/35273569/65138181-d8014200-da0a-11e9-9612-752012d1d257.png)

![image](https://user-images.githubusercontent.com/35273569/65138210-e4859a80-da0a-11e9-92dc-915a3fdd8b80.png)

**Comment by RavinderReddyF5** [comment]
Issues fixed with https://github.com/terraform-providers/terraform-provider-bigip/pull/165
