### ISSUE TITLE
resourceBigipAs3Create expects 200 response but is 202

### ISSUE THREAD

**Issue by mathianasj** [terraform-providers/terraform-provider-bigip#162]
When creating a new AS3 request to create an entry the code expects 200 but is getting 202 and causes the request to fail.

**Comment by papineni87** [comment]
can you paste the complete error output and also as3 json to check out any issue in as3 json itself ?

**Comment by papineni87** [comment]
are you using consul as service discovery with as3 ? or as3 itself for service discovery ? also what is as3 rpm you are using ?

**Comment by gageorsburn** [comment]
It's being used in conjunction with the openstack terraform that creates floating IP for member IPs and passes them into a JSON template to use with terraform as3.
AS3 3.11

**Comment by gageorsburn** [comment]
Seems like the request is taking longer than 45 seconds so it returns into an async request and returns a 202 response. Seems like there should probably be code in the provider to retry when the response code is 202 until the resource is actually created.

**Comment by focrensh** [comment]
Async behavior will be default and supported in the next release of BIG-IP provider.
