### ISSUE TITLE
Feature request: Updating ratio for a node (pool-member)

### ISSUE THREAD

**Issue by mayurikini** [terraform-providers/terraform-provider-bigip#163]
I have a pool with `load_balancing_mode` as `ratio-member`. I am able to set this via terraform. I have 2 nodes as pool members, and I want 1 node to have 99% of the traffic and the other to have 1%. I don't see an option to set ratio for a node. I would like to have ratio as an option.

I do see dynamic_ratio, but I am not sure if dynamic_ratio and ratio in big_ip are same. If I update the dynamic_ratio of the nodes, I am not able to see that change in bigip. I don't see a  field called dynamic ratio in bigip.

Let me know id I need to provide any more info.
Versions: Terraform v0.12.7 + provider.bigip v0.12.4
P.S I am new to terraform and big_ip concepts, I am following docs in https://www.terraform.io/docs/providers/bigip/, so correct me if I am wrong. :)

**Comment by RavinderReddyF5** [comment]
@mayurikini please find below document for overview on ratio based load balancing method:
https://support.f5.com/csp/article/K01052782

and also noticed we didnot have attribute for ratio setting on nodes in our resource files. creating internal JIRA Ticket to fix this issue[TER-123]

**Comment by mayurikini** [comment]
@RavinderReddyF5 Do we have an estimated date for getting ratio setting on nodes?

**Comment by RavinderReddyF5** [comment]
@mayurikini Will provide fix in couple of days.

**Comment by RavinderReddyF5** [comment]
@mayurikini 
Fix for this issue Merged with PR https://github.com/terraform-providers/terraform-provider-bigip/pull/174

Please verify and let us know

**Comment by mayurikini** [comment]
@RavinderReddyF5 I updated the ratio value for a node and while applying I could see the following in commandline:
Terraform will perform the following actions:

```
   bigip_ltm_node.node[1] will be created
  + resource "bigip_ltm_node" "node" {
      + address          = "********"
      + connection_limit = 0
      + dynamic_ratio    = (known after apply)
      + id               = (known after apply)
      + monitor          = "default"
      + name             = "/Common/XYZ"
      + rate_limit       = "disabled"
      + ratio            = 11
    }
```
In bigip, I did see the update for the node's ratio, but I don't see this update in pool > member. Here the ratio value is still 1. Is this expected?
![image](https://user-images.githubusercontent.com/16544484/67694190-f3982a80-f970-11e9-91ef-ddad0544981d.png)
![image](https://user-images.githubusercontent.com/16544484/67693827-5c32d780-f970-11e9-8817-7b8118845239.png)

**Comment by RavinderReddyF5** [comment]
@mayurikini 
we also noticed similar behaviour while adding ratio manually, this is nothing to do with terraform resource module, we are checking this behaviour with bigip team. can you please confirm this is reflecting by running some traffic test scenario.

**Comment by mayurikini** [comment]
@RavinderReddyF5 I did some load testing and looks like it is working as expected. I had kept ratio to be 9:1 for the pool members. 
![image](https://user-images.githubusercontent.com/16544484/67892158-1b7ac000-fb22-11e9-9ba4-260b7756734e.png)
First row is the pool, second and third row are the pool members.

**Comment by RavinderReddyF5** [comment]
Closing this Issue as fix already available
