### ISSUE TITLE
Docs for ltm_virtual_server incorrect

### ISSUE THREAD

**Issue by stobias123** [terraform-providers/terraform-provider-bigip#171]
it shows `rules` not `irules` in args list.

**Comment by dannyk81** [comment]
there's a PR to fix it https://github.com/terraform-providers/terraform-provider-bigip/pull/62

not sure why it hangs...

**Comment by RavinderReddyF5** [comment]
@stobias123 @dannyk81 
Fixed issue in : https://github.com/terraform-providers/terraform-provider-bigip/pull/172 and Merged to stable-website branch also. please check n confirm

**Comment by RavinderReddyF5** [comment]
Document is updated 👍 https://www.terraform.io/docs/providers/bigip/r/bigip_ltm_virtual_server.html

Closing this Issue.
