### ISSUE TITLE
Terraform Official docs way behind

### ISSUE THREAD

**Issue by stobias123** [terraform-providers/terraform-provider-bigip#182]
Some resources appear to be missing - I.E. `bigip_ltm_profile_ssl_client`

Provider main docs also don't surface the Env vars you can use.

https://github.com/terraform-providers/terraform-provider-bigip/blob/master/bigip/resource_bigip_ltm_profile_ssl_client.go

**Comment by papineni87** [comment]
Will update the documentation

**Comment by claycogg** [comment]
I'll close #188 as this is what I was asking for too.

Is it possible to get attribute documentation as well? Or do these resources not report attributes? I am referring to how  the AWS provider documentation documents the exported attributes available to the output.

Example:
https://www.terraform.io/docs/providers/aws/r/db_cluster_snapshot.html

**Comment by papineni87** [comment]
@stobias123:
we have updated terraform docs for ssl client/server profile . 
Can you please try validating your scenario with referring from docs below by local binary creation.
https://www.terraform.io/docs/providers/bigip/r/bigip_ltm_profile_client_ssl.html
https://www.terraform.io/docs/providers/bigip/r/bigip_ltm_profile_server_ssl.html

**Comment by papineni87** [comment]
This was fixed in the 1.1.0 release. If you are still having a problem with that release, please reopen this issue or file a new one.

**Comment by dannyk81** [comment]
@papineni87 kind of related, but I still don't see the content of this docs pr https://github.com/terraform-providers/terraform-provider-bigip/pull/88 in the official docs, any idea?

**Comment by RavinderReddyF5** [comment]
@dannyk81 Looks it Merged wayback into documentation branch, but anyway we will cross check and reopen/open issue for the same.

**Comment by papineni87** [comment]
@dannyk81  is this the below docs you are looking for ?https://www.terraform.io/docs/providers/bigip/r/bigip_ltm_pool_attachment.html

correct me if am wrong

**Comment by dannyk81** [comment]
> @dannyk81 is this the below docs you are looking for ?https://www.terraform.io/docs/providers/bigip/r/bigip_ltm_pool_attachment.html
> 
> correct me if am wrong

the PR I linked has additional information on how to import a pool attachment, I don't see it in the official doc you linked. 

this was indeed merged long ago, but for somenreason never made it to the official docs

**Comment by papineni87** [comment]
@dannyk81 i added the code back with the below pr

https://github.com/terraform-providers/terraform-provider-bigip/pull/210
