### ISSUE TITLE
Missing "database" entry for PostgreSQL monitor 

### ISSUE THREAD

**Issue by soumik612** [terraform-providers/terraform-provider-bigip#224]
I am trying to create a health monitor of type "Postgresql". Using TF, I am able to create one. However, TF plan/apply fails when I assign parameter "database".

My monitor resource looks like this:

resource "bigip_ltm_monitor" "MON_POSTGRESQL_EVAL" {
  name                 = "/Common/MON_POSTGRESQL_EVAL"
  parent                = "/Common/postgresql"
  send                   = "SELECT 'Test';"
  receive                = "Test"
  #receive_disable = 200
  interval                = 5
  timeout               = 16
  username            = "abcd"
  password             = "abcd1234"
  database              = "postgre"
}
I get the following error:

![image](https://user-images.githubusercontent.com/35273569/71994415-fc429200-3238-11ea-9e38-0e93864b5a71.png)

Working API reference:

'{"name":"MON_POSTGRESQL_EVAL","fullPath":"MON_POSTGRESQL_EVAL","type":"postgresql","database":"postgre","debug":"no","defaultsFrom":"/Common/postgresql","destination":"*:*","interval":30,"manualResume":"disabled","password":"abcd1234","recv":"123","send":"test","timeUntilUp":0,"timeout":91,"upInterval":0,"username":"abcd"}'

**Comment by papineni87** [comment]
database argument is not handled in code, will add that one

**Comment by GaddamSaketha** [comment]
**Provided the fix**
_Test Results are as below:_
=== RUN   TestAccProvider
--- PASS: TestAccProvider (0.00s)
=== RUN   TestAccBigipAs3_create
--- PASS: TestAccBigipAs3_create (10.89s)
=== RUN   TestAccBigipCmDevice_create
--- PASS: TestAccBigipCmDevice_create (4.21s)
=== RUN   TestAccBigipCmDevice_import
--- PASS: TestAccBigipCmDevice_import (3.73s)
=== RUN   TestAccBigipCmDevicegroup_create
--- PASS: TestAccBigipCmDevicegroup_create (3.58s)
=== RUN   TestAccBigipCmDevicegroup_import
--- PASS: TestAccBigipCmDevicegroup_import (1.21s)
=== RUN   TestAccBigipLtmDataGroup_create
--- PASS: TestAccBigipLtmDataGroup_create (8.40s)
=== RUN   TestAccBigipLtmDataGroup_import
--- PASS: TestAccBigipLtmDataGroup_import (8.26s)
=== RUN   TestAccBigipLtmIRule_create
--- PASS: TestAccBigipLtmIRule_create (3.52s)
=== RUN   TestAccBigipLtmIRule_import
--- PASS: TestAccBigipLtmIRule_import (3.77s)
=== RUN   TestAccBigipLtmMonitor_create
--- PASS: TestAccBigipLtmMonitor_create (14.36s)
=== RUN   TestAccBigipLtmMonitor_import
--- PASS: TestAccBigipLtmMonitor_import (3.74s)
=== RUN   TestAccBigipLtmNode_create
--- PASS: TestAccBigipLtmNode_create (4.55s)
=== RUN   TestAccBigipLtmNode_import
--- PASS: TestAccBigipLtmNode_import (7.30s)
=== RUN   TestAccBigipLtmNodeInvalid
--- PASS: TestAccBigipLtmNodeInvalid (0.01s)
=== RUN   TestAccBigipLtmNodeCreate
--- PASS: TestAccBigipLtmNodeCreate (0.05s)
=== RUN   TestAccBigipLtmPersistenceProfileCookieCreate
--- PASS: TestAccBigipLtmPersistenceProfileCookieCreate (2.81s)
=== RUN   TestAccBigipLtmPersistenceProfileCookieImport
--- PASS: TestAccBigipLtmPersistenceProfileCookieImport (1.97s)
=== RUN   TestAccBigipLtmPersistenceProfileDstAddrCreate
--- PASS: TestAccBigipLtmPersistenceProfileDstAddrCreate (3.53s)
=== RUN   TestAccBigipLtmPersistenceProfileDstAddrImport
--- PASS: TestAccBigipLtmPersistenceProfileDstAddrImport (2.72s)
=== RUN   TestAccBigipLtmPersistenceProfileSrcAddrCreate
--- PASS: TestAccBigipLtmPersistenceProfileSrcAddrCreate (2.13s)
=== RUN   TestAccBigipLtmPersistenceProfileSrcAddrImport
--- PASS: TestAccBigipLtmPersistenceProfileSrcAddrImport (3.68s)
=== RUN   TestAccBigipLtmPersistenceProfileSSLCreate
--- PASS: TestAccBigipLtmPersistenceProfileSSLCreate (2.95s)
=== RUN   TestAccBigipLtmPersistenceProfileSSLImport
--- PASS: TestAccBigipLtmPersistenceProfileSSLImport (1.94s)
=== RUN   TestAccBigipLtmPolicy_create
--- PASS: TestAccBigipLtmPolicy_create (4.49s)
=== RUN   TestAccBigipLtmPolicy_import
--- PASS: TestAccBigipLtmPolicy_import (7.16s)
=== RUN   TestAccBigipLtmPool_create
--- PASS: TestAccBigipLtmPool_create (8.92s)
=== RUN   TestAccBigipLtmPool_import
--- PASS: TestAccBigipLtmPool_import (12.52s)
=== RUN   TestAccBigipLtmfasthttp_create
--- PASS: TestAccBigipLtmfasthttp_create (7.55s)
=== RUN   TestAccBigipLtmProfilefasthttp_import
--- PASS: TestAccBigipLtmProfilefasthttp_import (4.36s)
=== RUN   TestAccBigipLtmProfileFastl4_create
--- PASS: TestAccBigipLtmProfileFastl4_create (4.09s)
=== RUN   TestAccBigipLtmProfileFastl4_import
--- PASS: TestAccBigipLtmProfileFastl4_import (3.84s)
=== RUN   TestAccBigipLtmProfileHttp2_create
--- PASS: TestAccBigipLtmProfileHttp2_create (2.77s)
=== RUN   TestAccBigipLtmProfileHttp2_modify
--- PASS: TestAccBigipLtmProfileHttp2_modify (5.52s)
=== RUN   TestAccBigipLtmProfileHttp2_import
--- PASS: TestAccBigipLtmProfileHttp2_import (2.78s)
=== RUN   TestAccBigipLtmProfileHttpcompress_create
--- PASS: TestAccBigipLtmProfileHttpcompress_create (3.01s)
=== RUN   TestAccBigipLtmProfileHttpcompress_import
--- PASS: TestAccBigipLtmProfileHttpcompress_import (3.58s)
=== RUN   TestAccBigipLtmProfileoneconnect_create
--- PASS: TestAccBigipLtmProfileoneconnect_create (1.78s)
=== RUN   TestAccBigipLtmProfileoneconnect_import
--- PASS: TestAccBigipLtmProfileoneconnect_import (2.96s)
=== RUN   TestAccBigipLtmProfileClientSsl_create
--- PASS: TestAccBigipLtmProfileClientSsl_create (3.63s)
=== RUN   TestAccBigipLtmProfileClientSsl_import
--- PASS: TestAccBigipLtmProfileClientSsl_import (3.08s)
=== RUN   TestAccBigipLtmProfileServerSsl_create
--- PASS: TestAccBigipLtmProfileServerSsl_create (2.25s)
=== RUN   TestAccBigipLtmProfileServerSsl_import
--- PASS: TestAccBigipLtmProfileServerSsl_import (3.09s)
=== RUN   TestAccBigipLtmProfileTcp_create
--- PASS: TestAccBigipLtmProfileTcp_create (2.88s)
=== RUN   TestAccBigipLtmProfileTcp_import
--- PASS: TestAccBigipLtmProfileTcp_import (2.30s)
=== RUN   TestAccBigipLtmsnat_create
--- PASS: TestAccBigipLtmsnat_create (3.09s)
=== RUN   TestAccBigipLtmsnat_import
--- PASS: TestAccBigipLtmsnat_import (3.98s)
=== RUN   TestAccBigipLtmsnatpool_create
--- PASS: TestAccBigipLtmsnatpool_create (1.21s)
=== RUN   TestAccBigipLtmsnatpool_import
--- PASS: TestAccBigipLtmsnatpool_import (3.15s)
=== RUN   TestAccBigipLtmVA_create
--- PASS: TestAccBigipLtmVA_create (4.37s)
=== RUN   TestAccBigipLtmVA_import
--- PASS: TestAccBigipLtmVA_import (2.54s)
=== RUN   TestAccBigipLtmVS_create
--- PASS: TestAccBigipLtmVS_create (4.17s)
=== RUN   TestAccBigipLtmVS_create_Defaultstate
--- PASS: TestAccBigipLtmVS_create_Defaultstate (6.08s)
=== RUN   TestAccBigipLtmVS_Modify_stateDisabledtoEnabled
--- PASS: TestAccBigipLtmVS_Modify_stateDisabledtoEnabled (8.47s)
=== RUN   TestAccBigipLtmVS_Modify_stateEnabledtoDisabled
--- PASS: TestAccBigipLtmVS_Modify_stateEnabledtoDisabled (6.08s)
=== RUN   TestAccBigipLtmVS_import
--- PASS: TestAccBigipLtmVS_import (4.18s)
=== RUN   TestAccBigipNetroute_create
--- PASS: TestAccBigipNetroute_create (8.84s)
=== RUN   TestAccBigipNetroute_import
--- PASS: TestAccBigipNetroute_import (23.63s)
=== RUN   TestAccBigipNetselfip_create
--- PASS: TestAccBigipNetselfip_create (1.14s)
=== RUN   TestAccBigipNetselfip_import
--- PASS: TestAccBigipNetselfip_import (18.44s)
=== RUN   TestAccBigipNetvlan_create
--- PASS: TestAccBigipNetvlan_create (2.64s)
=== RUN   TestAccBigipNetvlan_import
--- PASS: TestAccBigipNetvlan_import (4.45s)
=== RUN   TestAccSslCertificateImportToBigip
--- PASS: TestAccSslCertificateImportToBigip (1.13s)
=== RUN   TestAccSslKeyImportToBigip
--- PASS: TestAccSslKeyImportToBigip (4.46s)
=== RUN   TestAccBigipSysdns_create
--- PASS: TestAccBigipSysdns_create (2.67s)
=== RUN   TestAccBigipSysdns_import
--- PASS: TestAccBigipSysdns_import (2.05s)
=== RUN   TestAccBigipSysIapp_create
--- PASS: TestAccBigipSysIapp_create (5.08s)
=== RUN   TestAccBigipSysIapp_import
--- PASS: TestAccBigipSysIapp_import (4.12s)
=== RUN   TestAccBigipSysNtp_create
--- PASS: TestAccBigipSysNtp_create (11.56s)
=== RUN   TestAccBigipSysNtp_import
--- PASS: TestAccBigipSysNtp_import (1.66s)
=== RUN   TestAccBigipSysNtpInvalid
--- PASS: TestAccBigipSysNtpInvalid (0.01s)
=== RUN   TestAccBigipSysProvision_create
--- PASS: TestAccBigipSysProvision_create (4.42s)
=== RUN   TestAccBigipSysProvision_import
--- PASS: TestAccBigipSysProvision_import (2.44s)
=== RUN   TestAccBigipSyssnmp_create
--- PASS: TestAccBigipSyssnmp_create (2.28s)
=== RUN   TestAccBigipSyssnmp_import
--- PASS: TestAccBigipSyssnmp_import (3.78s)
=== RUN   TestValidStringValue
--- PASS: TestValidStringValue (0.00s)
=== RUN   TestInvalidStringValue
--- PASS: TestInvalidStringValue (0.00s)
=== RUN   TestF5NameString
--- PASS: TestF5NameString (0.00s)
=== RUN   TestF5NameSet
--- PASS: TestF5NameSet (0.00s)
=== RUN   TestF5NameList
--- PASS: TestF5NameList (0.00s)
=== RUN   TestValidateEnabledDisabledString
--- PASS: TestValidateEnabledDisabledString (0.00s)
=== RUN   TestValidateReqPrefDisabledString
--- PASS: TestValidateReqPrefDisabledString (0.00s)

**Comment by papineni87** [comment]
@soumik612 can you pull the latest code and check the fix ?

**Comment by soumik612** [comment]
@papineni87 : Has this fix been pushed to the official TF provider as well ?

**Comment by papineni87** [comment]
Yes

**Comment by soumik612** [comment]
@papineni87 ,
Thanks. It works fine if I use this provider.
However, fails when I use the official Terraform F5 provider.
Any idea when HashiCorp will push this in the official repo ?
 
![image](https://user-images.githubusercontent.com/35273569/80576613-ca328700-8a05-11ea-967b-9f4b13ce5fa7.png)

**Comment by RavinderReddyF5** [comment]
@soumik612 

I Just verified with Hashicorp release binary (v1.1.2) about issue, but looks fix is available in same. could please cross verify on the release version as below highlighted lines
 
 
HYD-ML-00064448:terraform-provider-bigip-1.12 chinthalapalli$ terraform apply
2020/04/29 21:03:49 [INFO] Terraform version: 0.12.12 
2020/04/29 21:03:49 [INFO] Go runtime version: go1.12.9
2020/04/29 21:03:49 [INFO] CLI args: []string{"/usr/local/bin/terraform", "apply"}
2020/04/29 21:03:49 [DEBUG] Attempting to open CLI config file: /Users/chinthalapalli/.terraformrc
2020/04/29 21:03:49 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/04/29 21:03:49 [INFO] CLI command args: []string{"apply"}
2020/04/29 21:03:49 [DEBUG] New state was assigned lineage "1b3319ca-66fd-4593-30e4-1cb33692ccbf"
2020/04/29 21:03:49 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2020/04/29 21:03:49 [DEBUG] checking for provider in "."
2020/04/29 21:03:49 [DEBUG] checking for provider in "/usr/local/bin"
2020/04/29 21:03:49 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2020/04/29 21:03:49 [DEBUG] found provider "terraform-provider-bigip_v1.1.2_x4"
2020/04/29 21:03:49 [DEBUG] **found valid plugin: "bigip", "1.1.2", "/Users/chinthalapalli/Downloads/terraform-provider-bigip-1.12/.terraform/plugins/darwin_amd64/terraform-provider-bigi
p_v1.1.2_x4"**
 
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
2020/04/29 21:03:51 [DEBUG] command: asking for input: "Do you want to perform these actions?"
  + create
 
Terraform will perform the following actions:
 
  # bigip_ltm_monitor.monitor will be created
  + resource "bigip_ltm_monitor" "monitor" {
      + adaptive       = (known after apply)
      + adaptive_limit = (known after apply)
      + compatibility  = (known after apply)
      + database       = "postgres"
      + destination    = (known after apply)
      + id             = (known after apply)
      + interval       = 999
      + ip_dscp        = (known after apply)
      + manual_resume  = (known after apply)
      + mode           = (known after apply)
      + name           = "/Common/terraform_monitor"
      + parent         = "/Common/http"
      + reverse        = (known after apply)
      + send           = "GET /some/path\\r\\n"
      + time_until_up  = (known after apply)
      + timeout        = 999
      + transparent    = (known after apply)
    }
 
Plan: 1 to add, 0 to change, 0 to destroy.
 
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
 
  Enter a value: yes
 
2020/04/29 21:03:53 [INFO] backend/local: apply calling Apply
2020/04/29 21:03:53 [INFO] terraform: building graph: GraphTypeApply
 
2020-04-29T21:03:53.847+0530 [DEBUG] plugin.terraform-provider-bigip_v1.1.2_x4: 2020/04/29 21:03:53 [INFO] Initializing BigIP connection
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
