### ISSUE TITLE
bigip_ltm_virtual_server stateless option

### ISSUE THREAD

**Issue by jack78901** [terraform-providers/terraform-provider-bigip#240]
Hello,

On the newer versions of the BIG-IP LTM (v14.1.06 +) there is a new Stateless type, that actually turns on a configuration on the backend for a stateless = true.

In a postman call to the API, you can see it actually returns as: 
    "stateless": true,

Is there a plan to have Terraform manage this option for the resource bigip_ltm_virtual_server? I would like to make sure that it is enforced that this does not get set.

Thank you

**Comment by mdditt2000** [comment]
The terraform provider wont set the stateless state. Can you please share the API call that you are trying so we can verify. Thank you! 

Btw for fast access to the BIGIP terraform folks please can you open issues at https://github.com/F5Networks/terraform-provider-bigip/issues

**Comment by focrensh** [comment]
If this is still needed. Please open a new issue on the repository above. Thanks
