### ISSUE TITLE
Cannot create bigip_ssl_key or bigip_ssl_certificate with LDAP account

### ISSUE THREAD

**Issue by ajchiarello** [terraform-providers/terraform-provider-bigip#246]
I originally posted this issue in #226 - since then, we have determined that the problem is that it does not work when using an LDAP account, only a local account. We opened a ticket with F5, and they said that this is because the 'Content-Range' header is not being set - in their example, the header was set to 'Content-Range: 1-1184/1184'. Can you confirm whether ssl resources should be working when using LDAP authentication?

**Comment by RavinderReddyF5** [comment]
@ajchiarello 
we are setting 'Content-Range' header when we copying certificate/key on to BIGIP, 


please find Header Request for same:
```
{Method:POST URL:https://10.145.65.170/mgmt/shared/file-transfer/uploads/servercert.crt Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Authorization:[Basic YWRtaW46RjVzaXRlMDI=] Content-Range:[0-1195/1196] Content-Type:[application/octet-stream]] Body:{Reader:0xc0002aa030} GetBody:0x13664e0 ContentLength:1196 TransferEncoding:[] Close:false Host:10.145.65.170 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc0000ee000}
```

**Comment by ajchiarello** [comment]
Thanks @RavinderReddyF5 - can you confirm whether LDAP accounts should work when creating these resources?

**Comment by RavinderReddyF5** [comment]
@ajchiarello 

Are you talking user authentication is enabled for LDAP instead local as shown in snapshot?

![image](https://user-images.githubusercontent.com/45624469/74824589-68cba900-532e-11ea-95e2-2e2b28a9e1fc.png)

If your answer is yes, we didnot have support for it. i am looking into details how much effort it would require

**Comment by RavinderReddyF5** [comment]
@ajchiarello 
I also tried created dummy LDAP authentication as shown in below

![image](https://user-images.githubusercontent.com/45624469/74825373-d1ffec00-532f-11ea-9a7e-85ee6107ffdf.png)


but i didnot see any issue, i am able to copy certificate, can you please what is configuration set by you for ldap authentication.?

**Comment by ajchiarello** [comment]
@RavinderReddyF5 Here is our config: 
![image001](https://user-images.githubusercontent.com/50917524/75250658-cf294f00-57a6-11ea-91d0-71e453ccdd9e.png)

**Comment by ajchiarello** [comment]
@RavinderReddyF5 Were you able to replicate the issue with the configuration screenshot I provided?

**Comment by RavinderReddyF5** [comment]
@ajchiarello I am not able to reproduce this issue in my local setup, is it possible to share setup? hope u have tried same using python script which i have shared earlier.

**Comment by ajchiarello** [comment]
@RavinderReddyF5 We've moved to using RADIUS authentication, and that is working fine - we just didn't have any more time to troubleshoot the openLDAP authentication issues.

**Comment by focrensh** [comment]
@ajchiarello Thank you for the info. If you need further investigation on this please include the example config file you are using and reopen the issue.
