### ISSUE TITLE
Is it possible at this time to use count with the BIG-IP provider? or modules?

### ISSUE THREAD

**Issue by scshitole** [terraform-providers/terraform-provider-bigip#247]
This is the only way to manage multiple BIG-IPs with ease.. Using alias or any other workarounds is simply not sufficient.

**Comment by dannyk81** [comment]
count is not available/possible for provider block.

modules are expected to support both count and the new for_each attributes, not sure when that will happen, you can track the progress here: https://github.com/hashicorp/terraform/issues/17519

**Comment by focrensh** [comment]
Closing as the issue @dannyk81 mentioned covers the upstream concern.
