### ISSUE TITLE
add "content list" For bigip_ltm_profile_httpcompress resource

### ISSUE THREAD

**Issue by vikram-chandrakanth** [terraform-providers/terraform-provider-bigip#25]
Hi, 

Currently , we cannot add the content list to the http_compress via the "bigip_ltm_profile_httpcompress" resource

example of adding the following "text/javascript, application/javascript" to the content list 

Regards,
Vikram

**Comment by scshitole** [comment]
@vikram-chandrakanth added content include - exclude field #36
