### ISSUE TITLE
v1.1.2 changed the contract of the `bigip_as3` resource

### ISSUE THREAD

**Issue by jakauppila** [terraform-providers/terraform-provider-bigip#267]
With the release of v1.1.2  the `bigip_as3` resource had the `config_name` attribute named to `tenant_name` breaking existing configurations.

While I don't disagree with the change, this is not something I would expect to have been done in a patch release, but rather went through the appropriate motions as described in [Hashicorp's  Deprecations, Removals and Renames best practices](https://www.terraform.io/docs/extend/best-practices/deprecations.html)

**Comment by papineni87** [comment]
@jakauppila sure, will follow hashicorp best practices

**Comment by RavinderReddyF5** [comment]
Fixed in v1.2.0
