### ISSUE TITLE
Terraform plan doesn't match apply

### ISSUE THREAD

**Issue by stobias123** [terraform-providers/terraform-provider-bigip#277]
Given a scenario where a `ltm_node` _already_ exists called `node1` and I have a file that creates a new file as shown....

```
resource "bigip_ltm_node" "node" {
  name             = "/Common/node1"
   ...
}
```

The plan will show success and 1 node to add.

When I run the apply, I get a failure and partial resource creation. 
```
Error: Error modifying node /Common/node1: HTTP 409 :: {“code”:409,“message”:“01020066:3: The requested Node (/Common/node1) already exists in partition Common.“,”errorStack”:[],“apiError”:3}
```
Why does my plan not fail showing the resource already exists?

**Comment by dkulchinsky** [comment]
plan checks diff between state and configuration (your tf files), if the node you just added in your terraform config already exist on the device you will get the above error and this is expected.

to reconcile the this, you should import the resource from the device to the terraform state (using `terraform import` command)
