### ISSUE TITLE
stuck on "Acquiring state lock"

### ISSUE THREAD

**Issue by the-player777** [terraform-providers/terraform-provider-bigip#28]
Hello, 

I try to do a "terraform plan" on our F5 (basically I'm just trying to create a node), but terraform is stuck on "Acquiring state lock". No additionnal logs are provided even if I set TF_LOG to TRACE:

`$ sudo TF_LOG=TRACE CHECKPOINT_DISABLE=1 terraform plan

2018/12/06 17:34:59 [INFO] Terraform version: 0.11.9  4e44b41c8bc1b533d14f9939690adf09e3d2a2be

2018/12/06 17:34:59 [INFO] Go runtime version: go1.11.1

2018/12/06 17:34:59 [INFO] CLI args: []string{"/usr/local/bin/terraform", "plan"}

2018/12/06 17:34:59 [DEBUG] Attempting to open CLI config file: /root/.terraformrc

2018/12/06 17:34:59 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.

2018/12/06 17:34:59 [INFO] CLI command args: []string{"plan"}

2018/12/06 17:34:59 [INFO] command: empty terraform config, returning nil

2018/12/06 17:34:59 [DEBUG] command: no data state file found for backend config

2018/12/06 17:34:59 [DEBUG] New state was assigned lineage "768aaff6-cbf2-fb81-1a60-f2937de8db52"

2018/12/06 17:34:59 [INFO] command: backend initialized: <nil>

2018/12/06 17:34:59 [DEBUG] checking for provider in "."

2018/12/06 17:34:59 [DEBUG] checking for provider in "/usr/local/bin"

2018/12/06 17:34:59 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"

2018/12/06 17:34:59 [DEBUG] found provider "terraform-provider-bigip_v0.12.0_x4"

2018/12/06 17:34:59 [DEBUG] found valid plugin: "bigip", "0.12.0", "/home/[...]/.terraform/plugins/linux_amd64/terraform-provider-bigip_v0.12.0_x4"

2018/12/06 17:34:59 [DEBUG] checking for provisioner in "."

2018/12/06 17:34:59 [DEBUG] checking for provisioner in "/usr/local/bin"

2018/12/06 17:34:59 [DEBUG] checking for provisioner in ".terraform/plugins/linux_amd64"

2018/12/06 17:34:59 [INFO] command: backend <nil> is not enhanced, wrapping in local

2018/12/06 17:34:59 [INFO] backend/local: starting Plan operation

Acquiring state lock. This may take a few moments...
`
I tried to wait for 20 minutes without any change.

Thanks in advance for your help.

**Comment by dannyk81** [comment]
`Acquiring state lock` is a pure Terraform operation where the relevant mechanism is invoked to lock the state, either local or remote (i.e. `s3`)

Are things working when removing the bigip definitions from your terraform configuration?

Have you tried strace`ing the terraform process when it's stuck to see what kind of syscalls it's doing?

**Comment by scshitole** [comment]
@the-player777 @dannyk81  should I close this if this is not related to provider ?
