### ISSUE TITLE
resource_bigip_command.go missing from latest release

### ISSUE THREAD

**Issue by Random6554** [terraform-providers/terraform-provider-bigip#280]
Hey!

The documentation has been added to support resource_bigip_command.go however the code is not included in the latest release. Is this intentional?

**Comment by RavinderReddyF5** [comment]
@Random6554 
Thanks for bringing this issue for notice, this resource support is getting added in coming up release, documentation is also intended for next release , but as terraform.io updates documentation directly from terraform provider repo `stable-website` branch, it reflected same.

**Comment by Random6554** [comment]
Cool, I have added locally so I can start using it, awesome work with this btw and thanks for a quick response.
