### ISSUE TITLE
AS3 apply fails on Terraform

### ISSUE THREAD

**Issue by andrescolodrero** [terraform-providers/terraform-provider-bigip#294]
Im testing a simple AS3 declaration.

With POST or Powershell, it is pretty fast and it works (after fixing some issue with appsvc rpm).
I like the way all changhes on AS3 declaration are idempotent.

But im having issues with terraform, same AS3 doesnt work. Apply fails after more than 5 minutes

Here the as3 code and below terraform and restnoded error when executing from "Terraform".

`{
   "class": "AS3",
   "action": "deploy",
   "declaration": {
       "class": "ADC",
       "schemaVersion": "3.0.0",
       "id": "urn:uuid:8a759300-9984-44a8-85d0-748d4f2438e1",
       "Tenantandres": {
           "class": "Tenant",
           "HTTP_Service": {
               "class": "Application",
               "template": "http",
               "serviceMain": {
                   "class": "Service_HTTP",
                   "virtualAddresses": [
                       "10.1.50.10"
                   ],
                   "pool": "adampool"
               },
               "adampool": {
                   "class": "Pool",
                   "monitors": [ "http" ],
                   "members": [
                     {
                       "servicePort": 80,
                       "serverAddresses": [
                          "10.1.50.100",
                          "10.1.50.101"
                       ]
                     }
                   ]
               }
           }
       }
   }
} `

Terraform plan:
`2020/05/22 09:49:29 [WARN] Provider "registry.terraform.io/-/bigip" produced an invalid plan for bigip_as3.as3-example1, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .as3_json: planned value cty.StringVal("{\"action\":\"deploy\",\"class\":\"AS3\",\"declaration\":{\"Tenantandres\":{\"HTTP_Service\":{\"adampool\":{\"class\":\"Pool\",\"members\":[{\"serverAddresses\":[\"10.1.50.100\",\"10.1.50.101\"],\"servicePort\":80}],\"monitors\":[\"http\"]},\"class\":\"Application\",\"serviceMain\":{\"class\":\"Service_HTTP\",\"pool\":\"adampool\",\"virtualAddresses\":[\"10.1.50.10\"]},\"template\":\"http\"},\"class\":\"Tenant\"},\"class\":\"ADC\",\"id\":\"urn:uuid:8a759300-9984-44a8-85d0-748d4f2438e1\",\"schemaVersion\":\"3.0.0\"}}") does not match config value cty.StringVal("{\r\n   \"class\": \"AS3\",\r\n   \"action\": \"deploy\",\r\n   \"declaration\": {\r\n       \"class\": \"ADC\",\r\n       \"schemaVersion\": \"3.0.0\",\r\n       \"id\": \"urn:uuid:8a759300-9984-44a8-85d0-748d4f2438e1\",\r\n       \"Tenantandres\": {\r\n           \"class\": \"Tenant\",\r\n           \"HTTP_Service\": {\r\n               \"class\": \"Application\",\r\n               \"template\": \"http\",\r\n               \"serviceMain\": {\r\n                   \"class\": \"Service_HTTP\",\r\n                   \"virtualAddresses\": [\r\n                       \"10.1.50.10\"\r\n                   ],\r\n                   \"pool\": \"adampool\"\r\n               },\r\n               \"adampool\": {\r\n                   \"class\": \"Pool\",\r\n                   \"monitors\": [ \"http\" ],\r\n                   \"members\": [\r\n                     {\r\n                       \"servicePort\": 80,\r\n                       \"serverAddresses\": [\r\n                          \"10.1.50.100\",\r\n                          \"10.1.50.101\"\r\n                       ]\r\n                     }\r\n                   ]\r\n               }\r\n           }\r\n       }\r\n   }\r\n} ")
`

but it continues and plan mention "1 resource to add".

Then after, terraform apply fails.
Error: Error creating json  Tenantandres: json: cannot unmarshal string into Go struct field Results1.code of type int64

  on main.tf line 7, in resource "bigip_as3" "as3-example1":
   7: resource "bigip_as3"  "as3-example1" {

If i check info in

/var/log/restnoded

`
Fri, 22 May 2020 09:56:10 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (connect EMFILE 127.0.0.1:8100 - Local (undefined:undefined))","level":"error"}
Fri, 22 May 2020 09:56:10 GMT - severe: [appsvcs] {"message":"Could not determine device port","level":"error"}
Fri, 22 May 2020 09:56:10 GMT - severe: [appsvcs] {"message":"Could not determine device port","level":"error"}
Fri, 22 May 2020 09:56:10 GMT - severe: [appsvcs] {"message":"Could not determine device port","level":"error"}
Fri, 22 May 2020 09:56:10 GMT - severe: [appsvcs] {"message":"Could not determine device port","level":"error"}
Fri, 22 May 2020 09:56:10 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (connect EMFILE 127.0.0.1:8100 - Local (undefined:undefined))","level":"error"}

....
Fri, 22 May 2020 09:56:10 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (connect EMFILE 127.0.0.1:8100 - Local (undefined:undefined))","level":"error"}
Fri, 22 May 2020 09:56:10 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (connect EMFILE 127.0.0.1:8100 - Local (undefined:undefined))","level":"error"}
Fri, 22 May 2020 09:56:10 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (connect EMFILE 127.0.0.1:8100 - Local (undefined:undefined))","level":"error"}
Fri, 22 May 2020 09:56:29 GMT - finest: socket 400 closed
`

**Comment by bastiortiz** [comment]
Hi @andrescolodrero,

I 'm having same issue where using POSTMAN works fine but it fails using Terraform.

Terraform Provider = `* provider.bigip: version = "~> 1.2"`
F5 AS3 Version = `f5-appsvcs 	3.19.1`

Output for `/var/log/restnoded/restnoded.log`

`Sat, 23 May 2020 02:38:35 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/ltm/data-group/internal/ failed (socket hang up)","level":"error"}
Sat, 23 May 2020 02:38:35 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (socket hang up)","level":"error"}
Sat, 23 May 2020 02:38:35 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (socket hang up)","level":"error"}
Sat, 23 May 2020 02:38:35 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (socket hang up)","level":"error"}
Sat, 23 May 2020 02:38:35 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (socket hang up)","level":"error"}
Sat, 23 May 2020 02:38:35 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (socket hang up)","level":"error"}
Sat, 23 May 2020 02:38:35 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/ltm/data-group/internal/ failed (socket hang up)","level":"error"}
Sat, 23 May 2020 02:38:35 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (socket hang up)","level":"error"}
Sat, 23 May 2020 02:38:35 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (socket hang up)","level":"error"}
Sat, 23 May 2020 02:38:35 GMT - severe: [appsvcs] {"message":"DELETE http://admin:XXXXXX@localhost:8100/mgmt/tm/ltm/data-group/internal/~Common~appsvcs~____appsvcs_lock Attempting to release global lock failed (connect ECONNREFUSED 127.0.0.1:8100)","level":"error"}
Sat, 23 May 2020 02:38:35 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (connect ECONNREFUSED 127.0.0.1:8100)","level":"error"}`

**Comment by RavinderReddyF5** [comment]
@andrescolodrero @bastiortiz

Issue identified and fixed in : https://github.com/F5Networks/terraform-provider-bigip Master branch.

Can you please clone latest master branch from :https://github.com/F5Networks/terraform-provider-bigip test your scenario and let me know if you still see any issues?

**Steps to test it locally:**
 ```
  mkdir -p $GOPATH/src/github.com/terraform-providers; cd $GOPATH/src/github.com/terraform-providers
  git clone https://github.com/F5Networks/terraform-provider-bigip.git
  cd terraform-provider-bigip
  export GOFLAGS=-mod=vendor
  go build
```

**Comment by RavinderReddyF5** [comment]
Issue Tracking internally with TER-353,TER-352

**Comment by bastiortiz** [comment]
Hi @RavinderReddyF5 ,

I followed your instructions:

` mkdir -p $GOPATH/src/github.com/terraform-providers; cd $GOPATH/src/github.com/terraform-providers
 git clone https://github.com/F5Networks/terraform-provider-bigip.git
 cd terraform-provider-bigip
 export GOFLAGS=-mod=vendor
 go build`

However, I'm still having the same issues and in the F5 output `/var/log/restnoded/restnoded.log` I can see the following logs:

`Sat, 23 May 2020 21:35:01 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (socket hang up)","level":"error"}
Sat, 23 May 2020 21:35:01 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/ltm/data-group/internal/ failed (socket hang up)","level":"error"}
Sat, 23 May 2020 21:35:01 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/ltm/data-group/internal/ failed (socket hang up)","level":"error"}
Sat, 23 May 2020 21:35:01 GMT - severe: [appsvcs] {"message":"PATCH http://localhost:8100/mgmt/tm/ltm/data-group/internal/~Common~appsvcs~dataStore failed (socket hang up)","level":"error"}
Sat, 23 May 2020 21:35:01 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/sys/folder/ failed (socket hang up)","level":"error"}
Sat, 23 May 2020 21:35:01 GMT - severe: [appsvcs] {"message":"PATCH http://localhost:8100/mgmt/tm/ltm/data-group/internal/~Common~appsvcs~dataStore failed (socket hang up)","level":"error"}
Sat, 23 May 2020 21:35:01 GMT - severe: [appsvcs] {"message":"POST http://localhost:8100/mgmt/tm/ltm/data-group/internal/ failed (socket hang up)","level":"error"}
Sat, 23 May 2020 21:35:01 GMT - warning: [appsvcs] {"message":"Unable to send telemetry data: connect ECONNREFUSED 127.0.0.1:8100","level":"warning"}
`

@andrescolodrero did you have better results?

Thanks,

**Comment by bastiortiz** [comment]
Hi @RavinderReddyF5,

I had replaced the provider location in `.terraform\plugins\windows_amd64` with the new one `terraform-provider-bigip.exe` and now it is working as expected:

`Apply complete! Resources: 1 added, 0 changed, 0 destroyed.`

I will continue testing. Thanks for your help!

**Comment by andrescolodrero** [comment]
@RavinderReddyF5 @bastiortiz 
after build on my machine with the provided instrucctions, it doesnt work for me. But i have less errors than before.
could someone provide the new provider? maybe my laptop is not building correctly.

Sun, 24 May 2020 17:24:44 GMT - warning: [appsvcs] {"message":"Unable to send telemetry data: Unable to register device: getaddrinfo ENOTFOUND product.apis.f5.com product.apis.f5.com:443","level":"warning"}
Sun, 24 May 2020 17:25:44 GMT - severe: [appsvcs] {"message":"Declaration failed: connection to http://admin:XXXXXX@localhost:8100/mgmt/tm/task/cli/script run cli script timed out","level":"error"}
Sun, 24 May 2020 17:26:44 GMT - warning: [appsvcs] {"message":"Error: failed to save BIG-IP config (connection to http://admin:XXXXXX@localhost:8100/mgmt/tm/task/sys/config create task save sys config timed out)","code":"ETIMEDOUT","level":"warning"}
Sun, 24 May 2020 17:26:50 GMT - finest: socket 408 closed

**Comment by RavinderReddyF5** [comment]
@andrescolodrero Can you please remove `.terraform` folder in your directory and build image with steps mentioned.

**Comment by andrescolodrero** [comment]
@RavinderReddyF5  inside my working folder of the project, i removed the exe from .terraform\plugins\windows_amd64 and add the new exe after i builded in my machine. im forgetting something?

**Comment by RavinderReddyF5** [comment]
@andrescolodrero that should be fine. are u still seeing issue?

**Comment by RavinderReddyF5** [comment]
@andrescolodrero Do you still this issues? if not can we close this issue?

**Comment by andrescolodrero** [comment]
@RavinderReddyF5  im having same error again, i want to be sure i setup properly the VMs.
i will try again and answer tomorrow

**Comment by focrensh** [comment]
If the new VM build you have still had an issue, please open a new issue around the specific errors for that. This issue had an issue fixed so i want to make sure to limit scope of it.
