### ISSUE TITLE
Can terraform delete or destroy a virtual server or pool created from the BIGIP GUI?

### ISSUE THREAD

**Issue by JerryAjaegbo** [terraform-providers/terraform-provider-bigip#303]
I am trying figure out how to modify load balancer objects that were not created using terraform. Is  this possible? Say for instance, terraform_delete_testVS was created in GUI, what would the "bigip_ltm_virtual_server" resource code look like to successfully delete the virtual server using terraform?

Any help  would be greatly appreciated.

Thanks
Jerry

**Comment by focrensh** [comment]
This is not a supported workflow. Terraform for BIG-IP provider will only manage state of objects it created.
