### ISSUE TITLE
`bigip_as3` should detect `Configuration operation in progress on device localhost, please try again in 2 minutes` and retry automatically

### ISSUE THREAD

**Issue by jakauppila** [terraform-providers/terraform-provider-bigip#304]
Our deployment pipeline ends up running multiple Terraform executions in parallel which has seen a few issues when running multiple executions against a single BigIP appliance with the following error:

```
bigip_as3.application_tenant: Creating...

Error: Error while Sending/Posting http request with AS3 json :{"code":503,"declarationFullId":"","message":"Error: Configuration operation in progress on device localhost, please try again in 2 minutes"}  <nil>

  on main.tf line 15, in resource "bigip_as3" "application_tenant":
  15: resource "bigip_as3" "application_tenant" {
```

It would be great if `resourceBigipAs3Update` could detect that error and retry (both timeout and retry count should be configurable ideally)

Here is Hashicorp's documentation on implementing retry logic within a resource: https://www.terraform.io/docs/extend/resources/retries-and-customizable-timeouts.html#retry

**Comment by focrensh** [comment]
There should be retry logic built in for this very use case in the current release. I will verify that it is live and update here.

**Comment by papineni87** [comment]
@jakauppila 

As @focrensh  mentioned  retry logic is there in current release and

we tried 2 scenerios around the parallel execution of bigip_as3.

1. Having multiple as3 resources in single .tf file with same bigip but different as3 jsons.
2. Running as3 resource simultaneously from different terminals with same bigip but different as3 jsons

In both the scenerios, it is the same bigip and executing parallel as3 resources. we did all CRUD operations on the as3 resource  without any issue.

How many as3 resources running in parallel ? i mean how many parallel executions against single bigip ?


Below is scenerio 1 with  3   as3 resources in single .tf file with CRUD operations


resource "bigip_as3" "as3-example1" {

as3_json = "${file("cs.json")}"

}

resource "bigip_as3" "as3-example2" {

as3_json = "${file("cs1.json")}"

}

resource "bigip_as3" "as3-example3" {

as3_json = "${file("cs2.json")}"

}

HYD-ML-00064444:terraform-providers sgaddam$ terraform apply
 
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 
Terraform will perform the following actions:
 
  # bigip_as3.as3-example1 will be created
  + resource "bigip_as3" "as3-example1" {
      + as3_json    = jsonencode(
            {
              + action      = "deploy"
              + class       = "AS3"
              + declaration = {
                  + Sample_02     = {
                      + Application_2      = {
                          + class       = "Application"
                          + serviceMain = {
                              + class            = "Service_HTTP"
                              + pool             = "web_pool2"
                              + virtualAddresses = [
                                  + "10.2.2.10",
                                ]
                            }
                          + template    = "http"
                          + web_pool2   = {
                              + class    = "Pool"
                              + members  = [
                                  + {
                                      + serverAddresses = [
                                          + "192.2.1.100",
                                          + "192.2.1.110",
                                        ]
                                      + servicePort     = 80
                                    },
                                ]
                              + monitors = [
                                  + "http",
                                ]
                            }
                        }
                      + class              = "Tenant"
                      + defaultRouteDomain = 0
                    }
                  + class         = "ADC"
                  + id            = "example-declaration-01"
                  + label         = "Sample 1"
                  + remark        = "Simple HTTP application with round robin pool"
                  + schemaVersion = "3.0.0"
                }
              + persist     = true
            }
        )
      + id          = (known after apply)
      + tenant_list = (known after apply)
    }
 
  # bigip_as3.as3-example2 will be created
  + resource "bigip_as3" "as3-example2" {
      + as3_json    = jsonencode(
            {
              + action      = "deploy"
              + class       = "AS3"
              + declaration = {
                  + Sample_03     = {
                      + Application_3      = {
                          + class       = "Application"
                          + serviceMain = {
                              + class            = "Service_HTTP"
                              + pool             = "web_pool3"
                              + virtualAddresses = [
                                  + "10.1.2.10",
                                ]
                            }
                          + template    = "http"
                          + web_pool3   = {
                              + class    = "Pool"
                              + members  = [
                                  + {
                                      + serverAddresses = [
                                          + "192.3.1.100",
                                          + "192.3.1.110",
                                        ]
                                      + servicePort     = 80
                                    },
                                ]
                              + monitors = [
                                  + "http",
                                ]
                            }
                        }
                      + class              = "Tenant"
                      + defaultRouteDomain = 0
                    }
                  + class         = "ADC"
                  + id            = "example-declaration-01"
                  + label         = "Sample 1"
                  + remark        = "Simple HTTP application with round robin pool"
                  + schemaVersion = "3.0.0"
                }
              + persist     = true
            }
        )
      + id          = (known after apply)
      + tenant_list = (known after apply)
    }
 
  # bigip_as3.as3-example3 will be created
  + resource "bigip_as3" "as3-example3" {
      + as3_json    = jsonencode(
            {
              + action      = "deploy"
              + class       = "AS3"
              + declaration = {
                  + Sample_04     = {
                      + Application_4      = {
                          + class       = "Application"
                          + serviceMain = {
                              + class            = "Service_HTTP"
                              + pool             = "web_pool4"
                              + virtualAddresses = [
                                  + "10.4.2.10",
                                ]
                            }
                          + template    = "http"
                          + web_pool4   = {
                              + class    = "Pool"
                              + members  = [
                                  + {
                                      + serverAddresses = [
                                          + "192.4.1.101",
                                          + "192.4.1.100",
                                        ]
                                      + servicePort     = 80
                                    },
                                ]
                              + monitors = [
                                  + "http",
                                ]
                            }
                        }
                      + class              = "Tenant"
                      + defaultRouteDomain = 0
                    }
                  + class         = "ADC"
                  + id            = "example-declaration-01"
                  + label         = "Sample 1"
                  + remark        = "Simple HTTP application with round robin pool"
                  + schemaVersion = "3.0.0"
                }
              + persist     = true
            }
        )
      + id          = (known after apply)
      + tenant_list = (known after apply)
    }
 
Plan: 3 to add, 0 to change, 0 to destroy.
 
 
Warning: Interpolation-only expressions are deprecated
 
  on main.tf line 7, in resource "bigip_as3" "as3-example1":
   7: as3_json = "${file("cs.json")}"
 
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.
 
Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.
 
(and 2 more similar warnings elsewhere)
 
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
 
  Enter a value: yes
 
bigip_as3.as3-example3: Creating...
bigip_as3.as3-example2: Creating...
bigip_as3.as3-example1: Creating...
bigip_as3.as3-example2: Creation complete after 7s [id=Sample_03]
bigip_as3.as3-example1: Still creating... [10s elapsed]
bigip_as3.as3-example3: Still creating... [10s elapsed]
bigip_as3.as3-example1: Creation complete after 17s [id=Sample_02]
bigip_as3.as3-example3: Still creating... [20s elapsed]
bigip_as3.as3-example3: Creation complete after 27s [id=Sample_04]
 
Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
HYD-ML-00064444:terraform-providers sgaddam$ vi cs.json 
HYD-ML-00064444:terraform-providers sgaddam$ vi cs1.json 
HYD-ML-00064444:terraform-providers sgaddam$ vi cs2.json 
HYD-ML-00064444:terraform-providers sgaddam$ terraform apply
bigip_as3.as3-example1: Refreshing state... [id=Sample_02]
bigip_as3.as3-example2: Refreshing state... [id=Sample_03]
bigip_as3.as3-example3: Refreshing state... [id=Sample_04]
 
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
 
Terraform will perform the following actions:
 
  # bigip_as3.as3-example1 will be updated in-place
  ~ resource "bigip_as3" "as3-example1" {
      ~ as3_json    = jsonencode(
          ~ {
                action      = "deploy"
                class       = "AS3"
              ~ declaration = {
                  ~ Sample_02     = {
                      ~ Application_2      = {
                            class       = "Application"
                            serviceMain = {
                                class            = "Service_HTTP"
                                pool             = "web_pool2"
                                virtualAddresses = [
                                    "10.2.2.10",
                                ]
                            }
                            template    = "http"
                          ~ web_pool2   = {
                                class    = "Pool"
                              ~ members  = [
                                  ~ {
                                      ~ serverAddresses = [
                                          - "192.2.1.100",
                                          + "192.2.1.101",
                                            "192.2.1.110",
                                        ]
                                        servicePort     = 80
                                    },
                                ]
                                monitors = [
                                    "http",
                                ]
                            }
                        }
                        class              = "Tenant"
                        defaultRouteDomain = 0
                    }
                    class         = "ADC"
                    id            = "example-declaration-01"
                    label         = "Sample 1"
                    remark        = "Simple HTTP application with round robin pool"
                    schemaVersion = "3.0.0"
                }
                persist     = true
            }
        )
        id          = "Sample_02"
        tenant_list = "Sample_02"
    }
 
  # bigip_as3.as3-example2 will be updated in-place
  ~ resource "bigip_as3" "as3-example2" {
      ~ as3_json    = jsonencode(
          ~ {
                action      = "deploy"
                class       = "AS3"
              ~ declaration = {
                  ~ Sample_03     = {
                      ~ Application_3      = {
                            class       = "Application"
                            serviceMain = {
                                class            = "Service_HTTP"
                                pool             = "web_pool3"
                                virtualAddresses = [
                                    "10.1.2.10",
                                ]
                            }
                            template    = "http"
                          ~ web_pool3   = {
                                class    = "Pool"
                              ~ members  = [
                                  ~ {
                                      ~ serverAddresses = [
                                          - "192.3.1.100",
                                          + "192.3.1.101",
                                            "192.3.1.110",
                                        ]
                                        servicePort     = 80
                                    },
                                ]
                                monitors = [
                                    "http",
                                ]
                            }
                        }
                        class              = "Tenant"
                        defaultRouteDomain = 0
                    }
                    class         = "ADC"
                    id            = "example-declaration-01"
                    label         = "Sample 1"
                    remark        = "Simple HTTP application with round robin pool"
                    schemaVersion = "3.0.0"
                }
                persist     = true
            }
        )
        id          = "Sample_03"
        tenant_list = "Sample_03"
    }
 
  # bigip_as3.as3-example3 will be updated in-place
  ~ resource "bigip_as3" "as3-example3" {
      ~ as3_json    = jsonencode(
          ~ {
                action      = "deploy"
                class       = "AS3"
              ~ declaration = {
                  ~ Sample_04     = {
                      ~ Application_4      = {
                            class       = "Application"
                            serviceMain = {
                                class            = "Service_HTTP"
                                pool             = "web_pool4"
                                virtualAddresses = [
                                    "10.4.2.10",
                                ]
                            }
                            template    = "http"
                          ~ web_pool4   = {
                                class    = "Pool"
                              ~ members  = [
                                  ~ {
                                      ~ serverAddresses = [
                                            "192.4.1.101",
                                          - "192.4.1.100",
                                          + "192.4.1.110",
                                        ]
                                        servicePort     = 80
                                    },
                                ]
                                monitors = [
                                    "http",
                                ]
                            }
                        }
                        class              = "Tenant"
                        defaultRouteDomain = 0
                    }
                    class         = "ADC"
                    id            = "example-declaration-01"
                    label         = "Sample 1"
                    remark        = "Simple HTTP application with round robin pool"
                    schemaVersion = "3.0.0"
                }
                persist     = true
            }
        )
        id          = "Sample_04"
        tenant_list = "Sample_04"
    }
 
Plan: 0 to add, 3 to change, 0 to destroy.
 
 
Warning: Interpolation-only expressions are deprecated
 
  on main.tf line 7, in resource "bigip_as3" "as3-example1":
   7: as3_json = "${file("cs.json")}"
 
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.
 
Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.
 
(and 2 more similar warnings elsewhere)
 
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
 
  Enter a value: yes
 
bigip_as3.as3-example1: Modifying... [id=Sample_02]
bigip_as3.as3-example2: Modifying... [id=Sample_03]
bigip_as3.as3-example3: Modifying... [id=Sample_04]
bigip_as3.as3-example3: Modifications complete after 10s [id=Sample_04]
bigip_as3.as3-example2: Still modifying... [id=Sample_03, 10s elapsed]
bigip_as3.as3-example1: Still modifying... [id=Sample_02, 10s elapsed]
bigip_as3.as3-example2: Modifications complete after 16s [id=Sample_03]
bigip_as3.as3-example1: Still modifying... [id=Sample_02, 20s elapsed]
bigip_as3.as3-example1: Modifications complete after 24s [id=Sample_02]
 
Apply complete! Resources: 0 added, 3 changed, 0 destroyed.
HYD-ML-00064444:terraform-providers sgaddam$ terraform destroy
bigip_as3.as3-example1: Refreshing state... [id=Sample_02]
bigip_as3.as3-example2: Refreshing state... [id=Sample_03]
bigip_as3.as3-example3: Refreshing state... [id=Sample_04]
 
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy
 
Terraform will perform the following actions:
 
  # bigip_as3.as3-example1 will be destroyed
  - resource "bigip_as3" "as3-example1" {
      - as3_json    = jsonencode(
            {
              - action      = "deploy"
              - class       = "AS3"
              - declaration = {
                  - Sample_02     = {
                      - Application_2      = {
                          - class       = "Application"
                          - serviceMain = {
                              - class            = "Service_HTTP"
                              - pool             = "web_pool2"
                              - virtualAddresses = [
                                  - "10.2.2.10",
                                ]
                            }
                          - template    = "http"
                          - web_pool2   = {
                              - class    = "Pool"
                              - members  = [
                                  - {
                                      - serverAddresses = [
                                          - "192.2.1.101",
                                          - "192.2.1.110",
                                        ]
                                      - servicePort     = 80
                                    },
                                ]
                              - monitors = [
                                  - "http",
                                ]
                            }
                        }
                      - class              = "Tenant"
                      - defaultRouteDomain = 0
                    }
                  - class         = "ADC"
                  - id            = "example-declaration-01"
                  - label         = "Sample 1"
                  - remark        = "Simple HTTP application with round robin pool"
                  - schemaVersion = "3.0.0"
                }
              - persist     = true
            }
        ) -> null
      - id          = "Sample_02" -> null
      - tenant_list = "Sample_02" -> null
    }
 
  # bigip_as3.as3-example2 will be destroyed
  - resource "bigip_as3" "as3-example2" {
      - as3_json    = jsonencode(
            {
              - action      = "deploy"
              - class       = "AS3"
              - declaration = {
                  - Sample_03     = {
                      - Application_3      = {
                          - class       = "Application"
                          - serviceMain = {
                              - class            = "Service_HTTP"
                              - pool             = "web_pool3"
                              - virtualAddresses = [
                                  - "10.1.2.10",
                                ]
                            }
                          - template    = "http"
                          - web_pool3   = {
                              - class    = "Pool"
                              - members  = [
                                  - {
                                      - serverAddresses = [
                                          - "192.3.1.101",
                                          - "192.3.1.110",
                                        ]
                                      - servicePort     = 80
                                    },
                                ]
                              - monitors = [
                                  - "http",
                                ]
                            }
                        }
                      - class              = "Tenant"
                      - defaultRouteDomain = 0
                    }
                  - class         = "ADC"
                  - id            = "example-declaration-01"
                  - label         = "Sample 1"
                  - remark        = "Simple HTTP application with round robin pool"
                  - schemaVersion = "3.0.0"
                }
              - persist     = true
            }
        ) -> null
      - id          = "Sample_03" -> null
      - tenant_list = "Sample_03" -> null
    }
 
  # bigip_as3.as3-example3 will be destroyed
  - resource "bigip_as3" "as3-example3" {
      - as3_json    = jsonencode(
            {
              - action      = "deploy"
              - class       = "AS3"
              - declaration = {
                  - Sample_04     = {
                      - Application_4      = {
                          - class       = "Application"
                          - serviceMain = {
                              - class            = "Service_HTTP"
                              - pool             = "web_pool4"
                              - virtualAddresses = [
                                  - "10.4.2.10",
                                ]
                            }
                          - template    = "http"
                          - web_pool4   = {
                              - class    = "Pool"
                              - members  = [
                                  - {
                                      - serverAddresses = [
                                          - "192.4.1.101",
                                          - "192.4.1.110",
                                        ]
                                      - servicePort     = 80
                                    },
                                ]
                              - monitors = [
                                  - "http",
                                ]
                            }
                        }
                      - class              = "Tenant"
                      - defaultRouteDomain = 0
                    }
                  - class         = "ADC"
                  - id            = "example-declaration-01"
                  - label         = "Sample 1"
                  - remark        = "Simple HTTP application with round robin pool"
                  - schemaVersion = "3.0.0"
                }
              - persist     = true
            }
        ) -> null
      - id          = "Sample_04" -> null
      - tenant_list = "Sample_04" -> null
    }
 
Plan: 0 to add, 0 to change, 3 to destroy.
 
 
Warning: Interpolation-only expressions are deprecated
 
  on main.tf line 7, in resource "bigip_as3" "as3-example1":
   7: as3_json = "${file("cs.json")}"
 
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.
 
Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.
 
(and 2 more similar warnings elsewhere)
 
Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.
 
  Enter a value: yes
 
bigip_as3.as3-example3: Destroying... [id=Sample_04]
bigip_as3.as3-example2: Destroying... [id=Sample_03]
bigip_as3.as3-example1: Destroying... [id=Sample_02]
bigip_as3.as3-example3: Destruction complete after 6s
bigip_as3.as3-example2: Still destroying... [id=Sample_03, 10s elapsed]
bigip_as3.as3-example1: Still destroying... [id=Sample_02, 10s elapsed]
bigip_as3.as3-example2: Destruction complete after 17s
bigip_as3.as3-example1: Still destroying... [id=Sample_02, 20s elapsed]
bigip_as3.as3-example1: Destruction complete after 26s
 
Destroy complete! Resources: 3 destroyed.

**Comment by jakauppila** [comment]
@papineni87 @focrensh Thanks, when I was looking in the code I was expecting to see that retry logic in the Terraform provider, but now I see that's being [handled in the client library itself](https://github.com/terraform-providers/terraform-provider-bigip/blob/master/vendor/github.com/f5devcentral/go-bigip/as3bigip.go#L228).

If I'm reading the logic correctly, it will continually check the status of any AS3 task ids until they are completed and then submit the post again.

**Comment by papineni87** [comment]
PostAs3Bigip() in below file

https://github.com/F5Networks/terraform-provider-bigip/blob/master/vendor/github.com/f5devcentral/go-bigip/as3bigip.go
