### ISSUE TITLE
Docs not updated?

### ISSUE THREAD

**Issue by Midacts** [terraform-providers/terraform-provider-bigip#49]
I've only checked [this doc](https://www.terraform.io/docs/providers/bigip/r/bigip_ltm_node.html), but it seems to not fully contain all the available settings as shown [here](https://github.com/terraform-providers/terraform-provider-bigip/blob/master/website/docs/r/bigip_ltm_node.html.markdown).

**Comment by scshitole** [comment]
@Midacts closing this as I have updated the docs
