### ISSUE TITLE
Creating FTP monitors

### ISSUE THREAD

**Issue by lynxx131** [terraform-providers/terraform-provider-bigip#59]
Are there any plans to allow FTP monitors to be created through the provider?

Similar question to #45 but probably needs a bit more work since the current monitor resource is geared towards monitors that work in a send / receive string basis.

**Comment by scshitole** [comment]
@lynxx131  this is fixed
```
cat master.tf 
provider "bigip" {
  address = "10.192.74.68"
  username = "admin"
  password = "admin"
}


resource "bigip_ltm_monitor" "test-ftp-monitor" {
	name = "/Common/ftp-test"
	parent = "/Common/ftp"
	interval          = 5
	time_until_up     = 0
	timeout           = 16
	destination       = "*:8008"
	filename = "somefile"
}

```

**Comment by lynxx131** [comment]
Thanks I'll get it checked out and give it a try.
