### ISSUE TITLE
Feature Request: Add ability to create a datagroup

### ISSUE THREAD

**Issue by foreverblue62** [terraform-providers/terraform-provider-bigip#63]
We use datagroups extensively for matchclass checks on IP address and URI redirections within iRule.

These datagroups are more dynamic and would benefit from being managed via Terraform.

**Comment by dannyk81** [comment]
This is already implemented and documented here: https://github.com/terraform-providers/terraform-provider-bigip/blob/master/website/docs/r/bigip_ltm_datagroup.html.markdown

I'm not sure why this isn't showing up on the official docs.

@scshitole could you check why the `datagroup` resource is missing in the documentation website?

**Comment by scshitole** [comment]
@dannyk81 @foreverblue62 looks like it is missed in the docs will add it.

**Comment by scshitole** [comment]
added and updated docs at https://www.terraform.io/docs/providers/bigip/r/bigip_ltm_datagroup.html
