### ISSUE TITLE
F5 ASM

### ISSUE THREAD

**Issue by arjuntony** [terraform-providers/terraform-provider-bigip#8]
Kindly let us know which field we have to edit in policywaf.json file in order to create new ASM Policy for the existing VIP.

**Comment by scshitole** [comment]
@arjuntony  with the resource you can only attach the already created ASM policy to the virtual server, you cannot create a new ASM policy.

**Comment by scshitole** [comment]
@arjuntony also you need Application service template on your bigip and bigip version supported is 12.X
