### ISSUE TITLE
Request: Cut a new release

### ISSUE THREAD

**Issue by DavidGamba** [terraform-providers/terraform-provider-bigip#85]
The last release is from September, it would be great if you can cut a new release so users don't have to get the latest changes by building the plugin themselves.

**Comment by scshitole** [comment]
@DavidGamba @dannyk81 I have requested them for the next release, will update you guys

**Comment by dannyk81** [comment]
@scshitole who's the maintainer from HashiCorp that works on this?

**Comment by dannyk81** [comment]
@scshitole looks like v0.12.1 was released 2 days ago :sweat_smile: 
![image](https://user-images.githubusercontent.com/24274156/56767571-11929180-677a-11e9-9557-e5e2a6142033.png)

but it's missing the few recent fixes :-(

do you think we can do v0.12.2? also include #96, this is in addition to #93 and #94 :pray:

**Comment by DavidGamba** [comment]
Is there a way to get the releases to have a changelog?

I don't want to have to look at the commits before deciding if I should migrate or not.
Additionally, I don't know if the newer releases are Terraform v0.12.x exclusive.

**Comment by dannyk81** [comment]
There is a changelog: https://github.com/terraform-providers/terraform-provider-bigip/blob/master/CHANGELOG.md

and AFAIK, both 0.12 and pre-0.12 terraform is supported, there's a compatibility table in the README https://github.com/terraform-providers/terraform-provider-bigip#f5-bigip-ltm-requirements

**Comment by RavinderReddyF5** [comment]
@DavidGamba 
as @dannyk81 suggested you can refer links for Changelog.md and supported BIGIP and terraform version metrics provided in repo.

**Comment by DavidGamba** [comment]
Thank you for the responses @dannyk81 and @RavinderReddyF5 , I actually just looked into the releases on Github and didn't look any further. So used to the Github workflow I guess.
Thanks!
